# Generated by Django 2.1.4 on 2018-12-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseapp', '0004_auto_20181214_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3),
        ),
    ]
