# Generated by Django 2.1.4 on 2018-12-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseapp', '0008_auto_20181214_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True),
        ),
    ]
