# Generated by Django 2.1.4 on 2018-12-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseapp', '0009_auto_20181214_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='by_weight',
            field=models.BooleanField(default=False),
        ),
    ]
