# Generated by Django 2.1.4 on 2018-12-16 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseapp', '0010_product_by_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.SmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
